var arrLang = {
    "en": {
        "email": "Email",
        "country": "Country",
        "starting_date": "Starting date:",
        "ending_date": "Ending date:",
        "code": "Code",
        "term": "These Terms will be governed by and interpreted in accordance with the laws of the State of Country, and you submit to the non-exclusive jurisdiction of the state and federal courts located in Country for the resolution of any disputes.",
        "submit": "Submit",
        "card_num": "Card number",
        "exp_date": "Expire Date",
        "card_name": "Cardholder name",
        "cv": "CCV/CVV",
        "payment": "Payment",
        "payment_text": "After the payment, you will receive your WalkWifi Code in your email.",
        "credit_card": "Credit Card",
        "Alipay": "Alipay",
        "TenPay": "TenPay",
        "action": "Actions",
        "action_text": "Your payment has been succesfully sent. Thank you. You will receive your WALKWIFI Code to the email adress ",
    },
    "cn": {
        "email": "电子邮件",
        "country": "国家",
        "starting_date": "开始日期:",
        "ending_date": "结束日期:",
        "code": "Code",
        "term": "这些条款将受国家/地区法律约束并根据国家/地区的法律解释，并且您服从国家和位于国家/地区的联邦法院的非专属管辖权，以解决任何争议。",
        "submit": "提交",
        "card_num": "卡号",
        "exp_date": "到期日期",
        "card_name": "持卡人姓名",
        "cv": "CCV/CVV",
        "payment": "付款",
        "payment_text": "付款后，您将通过电子邮件收到WalkWifi代码。",
        "credit_card": "信用卡",
        "Alipay": "Alipay",
        "TenPay": "TenPay",
        "action": "行动",
        "action_text": "您的付款已成功发送。谢谢。您将通过电子邮件地址收到WALKWIFI代码，",
    },
    "es": {
        "email": "Correo electrónico",
        "country": "País",
        "starting_date": "Fecha de inicio:",
        "ending_date": "Fecha final:",
        "code": "Código",
        "term": "Estos Términos se regirán e interpretarán de conformidad con las leyes del Estado del país, y usted se somete a la jurisdicción no exclusiva de los tribunales estatales y federales ubicados en el País para la resolución de cualquier disputa",
        "submit": " enviar",
        "card_num": "Número de tarjeta",
        "exp_date": "Fecha de caducidad",
        "card_name": "Nombre del titular de la tarjeta",
        "cv": "CCV / CVV",
        "payment": "Pago",
        "payment_text": "Después del pago, recibirá su código WalkWifi en su correo electrónico",
         "credit_card": "Tarjeta de crédito",
         "Alipay": "Alipay",
        "TenPay": "TenPay",
        "action": "Acciones",
        "action_text": "Su pago se ha enviado correctamente. Gracias. Recibirá su código WALKWIFI en la dirección de correo electrónico",
    },
    "fr": {
        "email": "Email",
        "country": "pays",
        "starting_date": "Date de début:",
        "ending_date": "Date de fin:",
        "code": "Code",
        "term": "Les présentes Conditions sont régies et interprétées conformément aux lois de l'État du pays, et vous vous soumettez à la juridiction non exclusive des tribunaux étatiques et fédéraux situés dans le pays pour la résolution des litiges.",
        "submit": "Submit",
        "card_num": "Numéro de carte",
        "exp_date": "Date d'expiration",
        "card_name": "nom du titulaire",
        "cv": "CCV / CVV",
        "payment": "Paiement",
        "payment_text": "Après le paiement, vous recevrez votre code WalkWifi dans votre courrier électronique.",
        "credit_card": "Carte de crédit",
        "Alipay": "Alipay",
        "TenPay": "TenPay",
        "action": "Actions",
        "action_text": "Votre paiement a été envoyé avec succès. Merci. Vous recevrez votre code WALKWIFI à l'adresse e-mail",
    }
};